[phases.setup]
nixPkgs = [
    'php82',
    'php82.extensions.curl',
    'php82.extensions.mbstring',
    'php82.extensions.xml',
    'php82.extensions.zip',
    'php82.extensions.gd',
    'php82.extensions.mysqli',
    'php82.extensions.pdo',
    'php82.extensions.pdo_mysql',
    'php82.extensions.bcmath',
    'php82.packages.composer',
    'nodejs-18_x',
    'yarn'
]

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm install'
]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8000} -t public"
